import {
  BadgeCheck,
  Boxes,
  Cable,
  CheckCircle2,
  CloudCog,
  Cloudy,
  Code2,
  Container,
  Cpu,
  Database,
  Fingerprint,
  GitPullRequest,
  HeartPulse,
  KeyRound,
  Network,
  PackageCheck,
  PackageOpen,
  Radar,
  Rocket,
  Route,
  ShieldCheck,
  ShieldEllipsis,
  Terminal,
  Waypoints,
  Workflow
} from "lucide-react";

export const pipelineIconMap = {
  pr: GitPullRequest,
  build: Terminal,
  security: ShieldCheck,
  registry: PackageCheck,
  helm: Boxes,
  deploy: Workflow,
  eks: CloudCog,
  data: Database,
  observability: HeartPulse,
  production: CheckCircle2
};

export const architectureIconMap = {
  dns: Route,
  shield: ShieldEllipsis,
  security: ShieldCheck,
  loadbalancer: Waypoints,
  ingress: Radar,
  controlplane: Cloudy,
  nodes: Cpu,
  autoscaling: Rocket,
  addons: PackageOpen,
  deploy: Workflow,
  registry: PackageCheck,
  rbac: BadgeCheck,
  pods: Container,
  services: Cable,
  helm: Boxes,
  vault: KeyRound,
  identity: Fingerprint,
  data: Database,
  config: Code2,
  network: Network,
  transit: Waypoints,
  observability: HeartPulse,
  operations: CheckCircle2
};
